FROM continuumio/miniconda:4.6.14

ENV SERVER_PORT 8000
ENV SRC_DIR /opt/waisn-tech-tools/

# copy source code
RUN mkdir -p $SRC_DIR
COPY ./environment-docker.yml $SRC_DIR
COPY ./waisntechtools/waisntechtools/ $SRC_DIR/waisntechtools/waisntechtools/
COPY ./waisntechtools/alerts/ $SRC_DIR/waisntechtools/alerts
COPY ./waisntechtools/manage.py $SRC_DIR/waisntechtools/manage.py

# set up conda env
WORKDIR $SRC_DIR
RUN conda env create -f environment-docker.yml

# run tests to sanity check image build
WORKDIR $SRC_DIR/waisntechtools
RUN . /opt/conda/etc/profile.d/conda.sh && \
    conda activate waisn-tech-tools && \
    python manage.py test

# expose runtime port - exposing debug port for now until creating production configuration
EXPOSE $SERVER_PORT

# set up some environment variables
ENV AUTH0_DOMAIN AUTH0_DOMAIN
ENV AUTH0_KEY AUTH0_KEY
ENV AUTH0_SECRET AUTH0_SECRET
ENV WAISN_AUTH_DISABLED TRUE

# run migrations
RUN . /opt/conda/etc/profile.d/conda.sh && \
    conda activate waisn-tech-tools && \
    python manage.py migrate

# run server
ENTRYPOINT . /opt/conda/etc/profile.d/conda.sh && \
    conda activate waisn-tech-tools && \
    python manage.py runserver 0.0.0.0:$SERVER_PORT
