# Generated by Django 2.1.4 on 2019-01-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('language', models.CharField(max_length=3)),
                ('subscription_state', models.CharField(max_length=20)),
                ('date_registered', models.DateTimeField(max_length=20)),
            ],
        ),
    ]
